version: '3.8'
services:
  bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - BOT_NAME=${BOT_NAME}
      - MEMORY_LIMIT=${MEMORY_LIMIT}
      - MONGO_URL=${MONGO_URL}
      - SESSION_STRING=${SESSION_STRING}
      - START_IMG=${START_IMG}
    restart: unless-stopped
